{% set name = "bentoml" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bentoml-{{ version }}.tar.gz
  sha256: 6bc4a4bb8f53b6ee70d1169ee439d89680f96771fbb3f11fb5eba13f96598c88

build:
  number: 0
  noarch: python
  entry_points:
    - bentoml=bentoml._internal.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=59.0
    - setuptools-scm >=6.2.3
    - wheel  
  run:
    - python >=3.7
    - aiofiles
    - aiohttp <=3.8.1
    - attrs >=21.1.0
    - backports.cached-property
    - cattrs >=21.1.0
    - chardet
    - circus
    - click >=7.0
    - cloudpickle
    - deepmerge
    # NOTE: exceptiongroup is available on channel: conda-forge/label/exceptiongroup_dev
    - exceptiongroup
    - filelock
    - fs
    - importlib-metadata
    - jinja2 >=3.0.1
    - numpy
    - opentelemetry-api ==1.9.0
    - opentelemetry-instrumentation ==0.28b0
    - opentelemetry-instrumentation-aiohttp-client ==0.28b0
    - opentelemetry-instrumentation-asgi ==0.28b0
    - opentelemetry-sdk ==1.9.0
    - opentelemetry-semantic-conventions ==0.28b0
    - opentelemetry-util-http ==0.28b0
    - packaging >=20.0
    - pathspec
    - pip-tools >=6.6.2
    - prometheus_client >=0.10.0,<0.14.0
    - psutil
    - pynvml <12
    - python-dateutil
    - python-dotenv >=0.20.0
    - python-json-logger
    - python-multipart
    - pyyaml >=5.0
    - requests
    - rich >=11.2.0
    - schema
    - simple-di >=0.1.4
    - starlette
    - typing-extensions >=4.0
    ## Converting the recipe to noarch: only build for python>=3.7
    # - backports.cached-property  # [py<38]
    # - exceptiongroup  # [py<=311]
    # - importlib-metadata  # [py<38]
    ## The following is necessary to pass pip-check
    - uvicorn

test:
  imports:
    - bentoml
  commands:
    - pip check
    - bentoml --help
  requires:
    - pip

about:
  home: https://github.com/bentoml/BentoML
  summary: 'Bentoml: The Unified Model Serving Framework'
  license: Apache-2.0
  license_file: LICENSE
  description: |
    BentoML simplifies ML model deployment and serves your models at production scale.

    PyPI: [https://pypi.org/project/bentoml/](https://pypi.org/project/bentoml/)

  doc_url: https://docs.bentoml.org/en/latest/
  dev_url: https://github.com/bentoml/BentoML

extra:
  recipe-maintainers:
    - sugatoray
    # co-maintainers from upstream
