{% set name = "bentoml" %}
{% set version = "1.2.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bentoml-{{ version }}.tar.gz
  sha256: 32643a711d607fab37a1b67e94bbe45f4bee3c8edc75299ee25e24ecac79d802

build:
  entry_points:
    - bentoml = bentoml_cli.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs >=0.3.0
    - pip
  run:
    - python >=3.8
    - jinja2 >=3.0.1
    - pyyaml >=5.0
    - aiohttp
    - attrs >=22.2.0
    - cattrs >=22.1.0,<23.2.0
    - circus >=0.17.0,!=0.17.2
    - click >=7.0
    - click-option-group
    - cloudpickle >=2.0.0
    - deepmerge
    - fs
    - httpx
    - inflection
    - numpy
    - nvidia-ml-py <12
    - opentelemetry-api ==1.20.0
    - opentelemetry-sdk ==1.20.0
    - opentelemetry-instrumentation ==0.41b0
    - opentelemetry-instrumentation-aiohttp-client ==0.41b0
    - opentelemetry-instrumentation-asgi ==0.41b0
    - opentelemetry-semantic-conventions ==0.41b0
    - opentelemetry-util-http ==0.41b0
    - packaging >=22.0
    - pathspec
    - pip-tools >=6.6.2
    - pip-requirements-parser >=31.2.0
    - prometheus_client >=0.10.0
    - psutil
    - pydantic <3
    - python-dateutil
    - python-multipart
    - python-json-logger
    - requests # No Longer in source
    - rich >=11.2.0
    - schema
    - simple-di >=0.1.4
    - starlette >=0.24.0
    - uvicorn
    - watchfiles >=0.15.0
    - tomli >=1.1.0
    - tomli-w

test:
  imports:
    - bentoml
  commands:
    - pip check
    - bentoml --help
  requires:
    - pip

about:
  home: https://github.com/bentoml/BentoML
  summary: 'Bentoml: The Unified Model Serving Framework'
  license: Apache-2.0
  license_file: LICENSE
  description: |
    BentoML simplifies ML model deployment and serves your models at production scale.

    PyPI: [https://pypi.org/project/bentoml/](https://pypi.org/project/bentoml/)

  doc_url: https://docs.bentoml.org/en/latest/
  dev_url: https://github.com/bentoml/BentoML

extra:
  recipe-maintainers:
    - rxm7706
    - sugatoray
    # co-maintainers from upstream
