{% set name = "bentoml" %}
{% set version = "1.3.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bentoml-{{ version }}.tar.gz
  sha256: 1628d3574be6d1880571e3cbfa047379502dd568abd7a616f5f3d544dd46ff76

build:
  entry_points:
    - bentoml = bentoml_cli.cli:cli
  noarch: python
  script:
    - sed -i '/"uv/d' ./pyproject.toml && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation  # [linux]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation  # [win or osx]
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs >=0.3.0
    - pip
  run:
    - python >={{ python_min }}
    - python >=3.9
    - jinja2 >=3.0.1
    - pyyaml >=5.0
    - aiohttp
    - attrs >=22.2.0
    - cattrs >=22.1.0,<23.2.0
    - kantoku >=0.18.1
    - click >=7.0
    - click-option-group
    - cloudpickle >=2.0.0
    - deepmerge
    - fs
    - httpx
    - inflection
    - numpy
    - nvidia-ml-py
    - opentelemetry-api >=1.20,<2.0
    - opentelemetry-sdk >=1.20,<2.0
    - opentelemetry-instrumentation >=0.41b0,<1.0
    - opentelemetry-instrumentation-aiohttp-client >=0.41b0,<1.0
    - opentelemetry-instrumentation-asgi >=0.41b0,<1.0
    - opentelemetry-semantic-conventions >=0.41b0,<1.0
    - opentelemetry-util-http >=0.41b0,<1.0
    - packaging >=22.0
    - pathspec
    - pip-requirements-parser >=31.2.0
    - prometheus_client >=0.10.0
    - psutil
    - pydantic <3
    - python-dateutil
    - python-multipart
    - python-json-logger
    - rich >=11.2.0
    - schema
    - simple-di >=0.1.4
    - starlette >=0.24.0
    - uvicorn >=0.22.0
    - watchfiles >=0.15.0
    - tomli >=1.1.0
    - tomli-w
    - httpx-ws >=0.6.0
    - aiosqlite >=0.20.0
    - uv >=0.5
    - questionary >=2.0.1
    - a2wsgi >=1.10.7
    - python-dotenv >=1.0.1

test:
  imports:
    - bentoml
  commands:
    # pip check fails because uv is part of base env, remove uv from pyproject.toml and enable pip check for linux only
    - pip check  # [linux]
    - bentoml --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bentoml/BentoML
  summary: 'Bentoml: The Unified Model Serving Framework'
  license: Apache-2.0
  license_file: LICENSE
  description: |
    BentoML simplifies ML model deployment and serves your models at production scale.

    PyPI: [https://pypi.org/project/bentoml/](https://pypi.org/project/bentoml/)

  doc_url: https://docs.bentoml.org/en/latest/
  dev_url: https://github.com/bentoml/BentoML

extra:
  recipe-maintainers:
    - rxm7706
    - sugatoray
    # co-maintainers from upstream
